# swagger-ui custom path
springdoc:
  show-actuator: false
  swagger-ui:
    path: /doc

server:
  shutdown: graceful
  error:
    include-message: always
    include-stacktrace: always
    include-exception: true
    include-binding-errors: always

spring:
  application:
    name: persistence-service
  lifecycle:
    timeout-per-shutdown-phase: 30s
  jpa:
    show-sql: true
    hibernate.ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        #        jdbc.time_zone: "Europe/Berlin"
        use_sql_comments: true
        format_sql: true
  datasource:
    url: jdbc:mysql://192.168.178.100:3306/db_persistence?serverTimezone=Europe/Berlin
    username: 'persistence'
    password: 'persistence123'
  liquibase:
#    enabled: true
    url: ${spring.datasource.url}
    user: 'liquibase_user'
    password: 'liquibase_user_321'
    change-log: classpath*:db/changelog/db.changelog-master.yaml
#    default-schema: public
#
#    flyway:
#      enabled: true
#      baseline-on-migrate: true

logging:
  level:
    "liquibase": INFO